# Docker Compose configuration

services:
  db:
    image: postgres:15
    env_file:
      - ".env.cred.example"
      - ".env.local.example"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready --username=$$POSTGRES_USER --dbname=$$POSTGRES_DB"
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    command: sh -c "redis-server --requirepass $$NAUTOBOT_REDIS_PASSWORD"
    env_file:
      - ".env.cred.example"
      - ".env.local.example"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "6379:6379"

  nautobot:
    build:
      context: .
      dockerfile: Dockerfile
    image: nautobot-topology:local
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - ".env.cred.example"
      - ".env.local.example"
    environment:
      prometheus_multiproc_dir: /tmp
    volumes:
      - "./nautobot_topology:/usr/local/lib/python3.14/site-packages/nautobot_topology"
      - "./nautobot_config.py:/opt/nautobot/nautobot_config.py"
      - "./dev_data.json:/opt/nautobot/dev_data.json"
    entrypoint: ""
    command: >
      sh -c "nautobot-server post_upgrade &&
             nautobot-server runserver 0.0.0.0:8080"

  celery:
    image: nautobot-topology:local
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - ".env.cred.example"
      - ".env.local.example"
    volumes:
      - "./nautobot_topology:/usr/local/lib/python3.14/site-packages/nautobot_topology"
      - "./nautobot_config.py:/opt/nautobot/nautobot_config.py"
    entrypoint: ""
    command: "nautobot-server celery worker -l INFO"

volumes:
  pgdata:
