# Generated by Django 5.2.13 on 2026-04-24 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nautobot_topology", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="topologylayout",
            options={
                "permissions": [
                    ("run_cablediscovery", "Can run cable discovery (LLDP/CDP)")
                ],
                "verbose_name": "Topology Layout",
                "verbose_name_plural": "Topology Layouts",
            },
        ),
    ]
