export const mockDiscoveryResults = [
  {
    local_interface: 'GigabitEthernet1/0/1',
    local_interface_type: 'interface',
    local_type: '1000base-t',
    local_interface_id: '11111111-1111-4111-a111-111111111111',
    local_device_id: 'aaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee',
    remote_device: 'core-switch-01',
    remote_device_id: '22222222-2222-4222-a222-222222222222',
    remote_interface: 'TenGigabitEthernet1/1',
    remote_interface_id: '33333333-3333-4333-a333-333333333333',
    remote_interface_type: 'interface',
    remote_type: '10gbase-x-sfpp',
    protocol: 'LLDP',
    is_matched: true,
    cable_exists: false,
    suggested_cable: 'cat6'
  },
  {
    local_interface: 'GigabitEthernet1/0/2',
    local_interface_type: 'interface',
    local_type: '1000base-t',
    local_interface_id: '44444444-4444-4444-a444-444444444444',
    local_device_id: 'aaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee',
    remote_device: 'unknown-switch',
    remote_device_id: null,
    remote_interface: 'eth0',
    remote_interface_id: null,
    remote_interface_type: 'interface',
    remote_type: 'other',
    protocol: 'CDP',
    is_matched: false,
    cable_exists: false,
    suggested_cable: 'cat6'
  },
  {
    local_interface: 'TenGigabitEthernet1/1/1',
    local_interface_type: 'interface',
    local_type: '10gbase-x-sfpp',
    local_lag: 'Port-channel10',
    local_lag_speed: 20,
    local_interface_id: 'dddddddd-dddd-4ddd-addd-dddddddddddd',
    local_device_id: 'aaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee',
    remote_device: 'leaf-02',
    remote_device_id: 'eeeeeeee-eeee-4eee-aeee-eeeeeeeeeeee',
    remote_interface: 'eth1/1',
    remote_interface_id: 'ffffffff-ffff-4fff-afff-ffffffffffff',
    remote_interface_type: 'interface',
    remote_type: '10gbase-x-sfpp',
    remote_lag: 'ae1',
    protocol: 'LLDP',
    is_matched: true,
    cable_exists: false,
    suggested_cable: 'fiber-lc'
  },
  {
    local_interface: 'TwentyFiveGigabitEthernet1/0/1',
    local_interface_type: 'interface',
    local_type: '25gbase-x-sfp28',
    local_interface_id: '25252525-2525-4525-a525-252525252525',
    local_device_id: 'aaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee',
    remote_device: 'spine-01',
    remote_device_id: 's1s1s1s1-s1s1-4s1s-as1s-s1s1s1s1s1s1',
    remote_interface: 'TwentyFiveGigabitEthernet1/1',
    remote_interface_id: 's2s2s2s2-s2s2-4s2s-as2s-s2s2s2s2s2s2',
    remote_interface_type: 'interface',
    remote_type: '25gbase-x-sfp28',
    protocol: 'LLDP',
    is_matched: true,
    cable_exists: false,
    suggested_cable: 'fiber-lc'
  },
  {
    local_interface: 'GigabitEthernet1/0/5',
    local_interface_type: 'interface',
    local_type: '1000base-t',
    local_interface_id: null,
    local_device_id: 'aaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee',
    remote_device: 'access-switch-05',
    remote_device_id: '99999999-9999-4999-a999-999999999999',
    remote_interface: 'GigabitEthernet0/1',
    remote_interface_id: null,
    remote_interface_type: 'interface',
    remote_type: '1000base-t',
    protocol: 'LLDP',
    is_matched: false,
    cable_exists: false,
    suggested_cable: 'cat6'
  },
  {
    local_interface: 'Port 1',
    local_interface_type: 'frontport',
    local_type: 'other',
    local_interface_id: 'aaaaaaaa-aaaa-4aaa-baaa-aaaaaaaaaaaa',
    local_device_id: 'aaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee',
    remote_device: 'patch-panel-01',
    remote_device_id: 'bbbbbbbb-bbbb-4bbb-bbbb-bbbbbbbbbbbb',
    remote_interface: 'Port 24',
    remote_interface_id: 'cccccccc-cccc-4ccc-cccc-cccccccccccc',
    remote_interface_type: 'rearport',
    remote_type: 'other',
    protocol: 'LLDP',
    is_matched: true,
    cable_exists: false,
    suggested_cable: 'fiber-lc'
  }
];
